server:
  port: 8888
spring:
  profiles:
    include: password
  cloud:
    gateway:
      routes:
        - id: backend_route
          uri: http://xxxx:xxxx 
          predicates:
            - Path=/bi/**
  #jackson配置
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      INDENT_OUTPUT: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace